export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILURE = "CREATE_PROJECT_FAILURE";

export const FETCH_PROJECT_BY_ID_REQUEST = "FETCH_PROJECT_BY_ID_REQUEST";
export const FETCH_PROJECT_BY_ID_SUCCESS = "FETCH_PROJECT_BY_ID_SUCCESS";
export const FETCH_PROJECT_BY_ID_FAILURE = "FETCH_PROJECT_BY_ID_FAILURE";

export const FETCH_PROJECTS_REQUEST = "FETCH_PROJECTS_REQUEST";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAILURE = "FETCH_PROJECTS_FAILURE";

export const SEARCH_PROJECT_REQUEST = "SEARCH_PROJECT_REQUEST";
export const SEARCH_PROJECT_SUCCESS = "SEARCH_PROJECT_SUCCESS";
export const SEARCH_PROJECT_FAILURE = "SEARCH_PROJECT_FAILURE";

export const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAILURE = "DELETE_PROJECT_FAILURE";

export const INVITE_TO_PROJECT_REQUEST = "INVITE_TO_PROJECT_REQUEST";
export const INVITE_TO_PROJECT_SUCCESS = "INVITE_TO_PROJECT_SUCCESS";
export const INVITE_TO_PROJECT_FAILURE = "INVITE_TO_PROJECT_FAILURE";

export const ACCEPT_PROJECT_INVITE_REQUEST = "ACCEPT_PROJECT_INVITE_REQUEST";
export const ACCEPT_PROJECT_INVITE_SUCCESS = "ACCEPT_PROJECT_INVITE_SUCCESS";
export const ACCEPT_PROJECT_INVITE_FAILURE = "ACCEPT_PROJECT_INVITE_FAILURE";
